<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql
select * from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [7]:
%%sql

select
  orderdate,
  quantity,
  netprice,
case
  when quantity >=3 and netprice >=100 then 'Multiple high Value Order'
  when netprice >= 100 then 'single high value Item'
  when quantity >=3 then 'multiple standard Items'
  else 'standard order'
end as order_type
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97             standard order
1  2015-01-01         1    659.78     single high value Item
2  2015-01-01         2     54.38             standard order
3  2015-01-01         4    286.69  Multiple high Value Order
4  2015-01-01         7    135.75  Multiple high Value Order
5  2015-01-01         3    434.30  Multiple high Value Order
6  2015-01-01         1     58.73             standard order
7  2015-01-01         3     74.99    multiple standard Items
8  2015-01-01         2    113.57     single high value Item
9  2015-01-01         1    499.45     single high value Item

In [11]:
#Finding the low and high net revenue for the product category
%%sql
select
  p.categoryname as category,
  sum(case when(s.quantity * s.netprice * s.exchangerate) < 398
  then (s.quantity * s.netprice * s.exchangerate) end) as low_net_revenue,
  sum(case when(s.quantity * s.netprice * s.exchangerate) > 398
  then (s.quantity * s.netprice * s.exchangerate) end) as high_net_revenue
from sales as s
left join product as p on s.productkey = p.productkey
group by
  p.categoryname
order by
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  low_net_revenue  high_net_revenue
0                          Audio       1759699.82        3553198.29
1        Cameras and camcorders         829242.04       17691118.62
2                    Cell phones       2862254.35       29748877.36
3                      Computers       2204185.96       88414836.09
4                 Games and Toys       1254038.18         414535.96
5                Home Appliances       1095190.74       25512054.79
6  Music, Movies and Audio Books       2862001.70        7726309.30
7                   TV and Video        980860.35       19484011.03

In [ ]:
()